GET http://localhost:3003/movies/

###


POST http://localhost:3003/movies/
Content-Type: application/json

{
  "director_id":6,
  "movie_name": "Jurassic Park",
  "lead_actor": "Jeff Goldblum"
}

###